['computercraft:computer_normal',
    'computercraft:computer_advanced',
    Item.of('computercraft:turtle_normal', '{RightUpgrade:"minecraft:diamond_pickaxe",RightUpgradeNbt:{Tag:{Damage:0}}}'),
    Item.of('computercraft:turtle_advanced', '{RightUpgrade:"minecraft:diamond_sword",RightUpgradeNbt:{Tag:{Damage:0}}}'),
    'create:gearbox',
    'create:mechanical_drill',
    'createbigcannons:cast_iron_block',
    'create:fluid_pipe',
    'create:track',
    'ae2:logic_processor',
    'create:electron_tube',
    'create:precision_mechanism',
    'ae2:calculation_processor',
    'ae2:engineering_processor',
    'ae2:molecular_assembler',
    'createaddition:tesla_coil',
    'create_sa:brass_drone_item',
    'create_sa:flamethrower',
    'littlelogistics:energy_tug',
    'simplemagnets:advancedmagnet']