JEIEvents.hideItems(event => {
    event.hide([
        'artifacts:charm_of_sinking',
        'artifacts:thorn_pendant',
        'artifacts:flame_pendant',
        'artifacts:power_glove',
        'artifacts:digging_claws',
        'artifacts:universal_attractor',
        'artifacts:aqua_dashers',
        'artifacts:kitty_slippers',
        'artifacts:flippers',
        'artifacts:lucky_scarf',
        'artifacts:cross_necklace',
        'artifacts:fire_gauntlet',
        'artifacts:obsidian_skull',
        'artifacts:superstitious_hat',
        'artifacts:scarf_of_invisibility',
        'artifacts:villager_hat',
        'artifacts:night_vision_goggles',
        'artifacts:snorkel',
        'artifacts:bunny_hoppers',
        Item.of('create_sa:brass_jetpack_chestplate', '{Damage:0}'),
        Item.of('create_sa:andesite_jetpack_chestplate', '{Damage:0}'),
        Item.of('create_sa:copper_jetpack_chestplate', '{Damage:0}'),
        'farmingforblockheads:market',
        Item.of('grapplemod:longfallboots', '{Damage:0}'),
        'grapplemod:rocketupgradeitem',
        'grapplemod:swingupgradeitem',
        'grapplemod:staffupgradeitem',
        'grapplemod:motorupgradeitem',
        'grapplemod:magnetupgradeitem',
        'grapplemod:forcefieldupgradeitem',
        'grapplemod:repeller',
        'grapplemod:launcheritem',
        'grapplemod:doubleupgradeitem',
        'grapplemod:throwupgradeitem',
        'grapplemod:limitsupgradeitem',
        'mininggadgets:upgrade_battery_1',
        'mininggadgets:upgrade_battery_2',
        'mininggadgets:upgrade_battery_3',
        'mininggadgets:upgrade_fortune_3',
        'pylons:harvester_pylon',
        'pylons:expulsion_pylon',
        'pylons:mob_filter',
        'pylons:player_filter',
        'scannable:entity_module',
        'scannable:friendly_entity_module',
        'scannable:hostile_entity_module',
        'scannable:block_module',
        'scannable:common_ores_module',
        'scannable:rare_ores_module',
        'scannable:fluid_module',
        'scannable:chest_module',
        'toms_storage:ts.inventory_cable',
        'toms_storage:ts.inventory_cable_framed',
        'toms_storage:ts.inventory_cable_connector',
        'toms_storage:ts.inventory_cable_connector_filtered',
        'toms_storage:ts.inventory_cable_connector_framed',
        'toms_storage:ts.inventory_hopper_basic',
        'toms_storage:ts.adv_wireless_terminal'
    ])
})

